dist: trusty
language: java
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/nbnuk/travis-build-configuration/master/travis_maven_settings_simple.xml
script: mvn clean install deploy
env:
  global:
  - secure: hYGIDhOQhFrzV1helfiDdbr7M/WH9RFw6sk0mkxxZLw8SLaHzMHpp51tbjL6PQRi6Dcn+y7dyUrI0p9PCWiT0apHxRZksxWWdxoK9Zt1gAX4fAoLl5k1ilnHqQSvQ9yWzYAtmvs0lZ5Do2Su5+UsMkDG1aVFkvnq/ZCHM+P3w1xZK9o8EWpIImUizfCj/aPBiyl/5BpAPK3SpctmUTcrjepAYs76SIRROFGcyDXvGt1za81znRoEnTH0y2s4nizWBaj1Z5kCjh3RFcEwZlKOUZd0U/GSAg/rOgV7RJPZ8uGYY3mk7grT69hgneecK6sN0XsSTg3CxuTfnhiAM5OcNF5nOwXcm/VLzuszonFlvU4PP3X6RKL8+a+uZECO3f2PZZa74iG0gu4KHoq87BW1Bcp8+Lr5+h697IIHw31/hqvWAjeoyRsxKVuu37COCDrrMPt11YvJNEHNgsfhxIKC5vYDtWMQvACegpARvH0150Jg5u8Of46dkvwONiqUv6x+tr9FoEYJUEdbhtvY1tPtlXRTYoyize2P15KUQGGYmOf3xAHx5JN6arcs8NuFz/pKdGAT9j0phoi1fd08RvatfVjVxgSuXCIyRRpgftXjMSYOK/fJwtYwk9EPC0n2m6TEARPmyNPbUquGVD90TgN3G69qgYyW3hJNBQb2kqtoNGk=
  - secure: OK1Z+OfEsg7f53AIK4wXFnKJgPLnAaV6iEm8XWm7uIrvTz8gBzI8uNevG+RBgbR9t7F63hTd86d4Jq9W7wb3bdZOre5CkfBc4n3F8vljStaLwAf6VLwGDrjntfDawobWgtJijZNAIdTfYwBODsuDWngS4Cu7CZhLNV6hYS26luvwPnyL5LFJeEtSt8u36CZAjntdn18q7jv7bt3kTZvR+XOQ7dAlizU6hg9d/Ms2ZBhQBm2TLnOfhiQn4fAKJ63DBOB+SEh9y/B8d0IfV1FvzXfQyx4A6c4S9C5oh/x552amAwPoD28x9EfXsPPlK8s0kydg01jei+2SobIwStff8Yih9ZvJmyFM+gc1I270QXwojul14PaxNKvyidXJy5h5ayAI84pBK8aHADYaGqYOxj3epEoJg3l8q1iM/dm9GGn7lS8LKTtzy7ldQjujVG+EZH8TUbnEuEBDSsU5P/89VimUqZhrCAbHl4Rfx6aT+JWWhxFfvrmrajj6GT7VjJnKEx3GojwRoONeTNlqbF+3QxJcJv8xdc17nWtH9bZmcBIGTmXrycfx5pr1SKmOilqSWmVvjOYaIrcaE7FruogZnNn5DUZBhna3vtyA7yBjOR2jeW4KNKZEE+FjSschOorWm7hlLI/K5pihNvVp5kA0dZDOSr7ZMadzb24RdgREUFg=
